spring:
   profile:
       active:
         - dev
---

spring:
   profile: dev   # 开发环境
       application:
              name：microstarcloud-config-dev
	      
 ---

 spring:
   profile: dev   # 测试环境
       application:
              name：microstarcloud-config-test

#请保存为UTF-8格式

